### ISSUE TITLE
Allow Milestones to be created and named inside projects

### ISSUE THREAD

**Issue by Aviorleking** [upstreamplugin/UpStream#281]
make milestone like [this](https://gitlab.com/gitlab-org/gitlab-ce/milestones) for example.
or make creating new milestones simpler for version milestone

**Comment by upstreamplugin** [comment]
Thanks for the suggestion @Aviorleking 

Sorry, I don't quite understand the request. Could you explain the changes more?

**Comment by deenison** [comment]
Sorry @Aviorleking didn't get it as well.

Wouldn't this be solved by just naming the milestones the versions you need? ie `v0.0.0`

**Comment by Aviorleking** [comment]
If I have multiple projects it will have a lot of milestones in the general milestone settings not linked each other

**Comment by Aviorleking** [comment]
for better explanation 
It would be better to make milestones projects specific

**Comment by upstreamplugin** [comment]
Hi @Aviorleking. Sorry, I'm still not 100% clear. 

By default, milestones are already project-specific like bugs and tasks.

**Comment by deenison** [comment]
I think I get it. Perhaps this would be the same as #285?

**Comment by Aviorleking** [comment]
Yep

**Comment by andergmartins** [comment]
We are working on this issue. Here is a list of items we still need to check:

- [ ] capability_type in the post type definition
- [ ] capabilities to access
- [ ] move to the Projects menu

**Comment by andergmartins** [comment]
This feature is now implemented and waiting to be released. Some minor new tasks will be handled in specific issues, mentioning this one.
